### ISSUE TITLE
Bench Metadata/Metadatum object for more structured / external ones ?

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#101]
Question for @fbaumgardt @balmas 

With more annotations coming up, we are basically adding layers and layers of complexity to MyCapytain while it should be mostly about texts and their metadata. We ended up building stuff such as the Metadata/Metadatum classes which are poor implementation of some more complex required tools (Every improvement takes time basically and often breaks stuff, such as namespace).

I am heavily questioning the importance of implementing it completely in MyCapytain and wonder if
simply enhancing/implementing https://github.com/RDFLib/rdflib-jsonld & https://github.com/RDFLib/rdflib into the Metadata object would make more sense.

This will set back the delivery of the tool but would allow for more experimentation later in a more structured way.

**Comment by balmas** [comment]
I think this is definitely worth considering, but my advice would be to get the full suite of tools (i.e. including Nemo and Nautilus) working with the latest MyCapytain code before embarking on this refactoring.
