### ISSUE TITLE
Error in resolver when a text is not present

### ISSUE THREAD

**Issue by sonofmun** [Capitains/MyCapytain#129]
The following code block:

```
from MyCapytain.resolvers.cts.local import CtsCapitainsLocalResolver
from MyCapytain.common.constants import Mimetypes


Repository = CtsCapitainsLocalResolver(["./tests/testing_data/latinLit"])
for text in Repository.texts:
    interactive_text = Repository.getTextualNode(text)
    plaintext = passage.export(Mimetypes.PLAINTEXT)
```
Sometimes produced the following error:

```
[Errno 2] No such file or directory: '/home/matt/OpenMigne/canonical-latinLit/data/phi1221/phi007/phi1221.phi007.perseus-lat1.xml'
```
I think it is because this file is mentioned in the /home/matt/OpenMigne/canonical-latinLit/data/phi1221/phi007/__cts__.xml` metadata file but it does not exist in the repository.

**Comment by sonofmun** [comment]
My hunch is that it is in these lines: https://github.com/Capitains/MyCapytain/blob/master/MyCapytain/resolvers/cts/local.py#L190-L191

**Comment by sonofmun** [comment]
Why did you close this issue?

**Comment by PonteIneptique** [comment]
Missclick :)

**Comment by sonofmun** [comment]
I will also take a look at this on the train to Leipzig this today.

**Comment by sonofmun** [comment]
Should I simply to do a try: except: statement here? Or is a more complex solution necessary?

**Comment by PonteIneptique** [comment]
I think checking that the file exist and issuing a warning if it does not should be enough, avoid try/except maybe ?
Check this for logging : https://github.com/Capitains/MyCapytain/blob/master/MyCapytain/resolvers/cts/local.py#L156

**Comment by PonteIneptique** [comment]
Don't use error but warning

**Comment by sonofmun** [comment]
Got it.

**Comment by sonofmun** [comment]
So `self.logger.warning` instead of self.logger.error`?

**Comment by PonteIneptique** [comment]
It's either warn or warning, but you got the idea yes :)

**Comment by sonofmun** [comment]
I am reopening because you mentioned that this might need to be changed in Nautilus as well. The code block in Nautilus is here: https://github.com/Capitains/Nautilus/blob/master/capitains_nautilus/cts/resolver.py#L284-L289
It already deals with this problem, although I don't know if this solution should be changed to be the same as the solution in MyCapytain.

**Comment by PonteIneptique** [comment]
The issue should be reopened in Nautilus.
Dealing with this could be done by raising an unknown collection is the file is unknown :)
