### ISSUE TITLE
Export to plain text also exports the TEI Header

### ISSUE THREAD

**Issue by sonofmun** [Capitains/MyCapytain#130]
You can see an example here: https://github.com/sonofmun/canonical-lat-test/blob/0.0.141/text/phi0448.phi001.perseus-eng2.txt

**Comment by PonteIneptique** [comment]
You can use .export(Mimetype.Text.., exclude=["tei:note", "tei:teiHeader"]) :)

**Comment by sonofmun** [comment]
I will give this a try today. If it works, I will close the issue.

**Comment by sonofmun** [comment]
That worked. Closing this issue
