### ISSUE TITLE
MIT or GNU GPL License

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#150]
It was shown to me that we had put MIT License in MyCapytain but actually we had GNU GPL on Nautilus.

I am more inclined to go for GPL on every Capitains package but what's your feeling here ?

Pinging @brosner @redmer

**Comment by balmas** [comment]
I generally prefer GPL but that's based upon familiarity more than anything else. I agree we should be consistent across all of the libraries.  My general approach is normally to use CC BY SA for all content, GPL for all software

**Comment by redmer** [comment]
I strongly prefer software licenses that don’t limit derivatives, so no GPL. I’ve heard that GPL in particular gets some to immediately gloss over a library. Also considering that 'commercial use' brings uncertainty as to what that constitutes. 

Especially if you want more contributors and more use of Capitains, I would suggest MIT or BSD.

**Comment by balmas** [comment]
ok, so sounds like we should go with MIT or BSD. No objections to that.

**Comment by PonteIneptique** [comment]
There is also Mozilla. I am open to making this is a vote. I just do not know what voting too to use...

**Comment by PonteIneptique** [comment]
After giving it some thoughts, I am moving the code bases to Mozilla Public License v2 which allows for multiple license in the same code base but is closer to my beliefs on this matter :)
