### ISSUE TITLE
Not finding cRefPattern should raise a specific error on local files

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#162]
Currently if `self.__findCRefPattern(self.resource)` fails in `MyCapytain/resources/texts/local/capitains/cts.py#441` you are most likely gonna get a IndexError. This should be a specific error that can be caught, such as `MissingRefsDecl`

**Comment by sonofmun** [comment]
It looks like the change will need to be done here on master: https://github.com/Capitains/MyCapytain/blob/25e1bebd20e27f773dbb748c24f0177c2d152d41/MyCapytain/resources/texts/local/capitains/cts.py#L467

**Comment by PonteIneptique** [comment]
I am actually wondering if it should happen in an else here https://github.com/Capitains/MyCapytain/blob/25e1bebd20e27f773dbb748c24f0177c2d152d41/MyCapytain/resources/texts/local/capitains/cts.py#L454

**Comment by sonofmun** [comment]
That makes sense.

**Comment by PonteIneptique** [comment]
I'd make it a normal Error rather an a key, because this is quite specific to MCpytain :)

**Comment by PonteIneptique** [comment]
Fixed :)
