### ISSUE TITLE
ReferenceError is a very wrong use of the Python built-in API

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#163]
Currently we wrongly use ReferenceError ( https://github.com/Capitains/MyCapytain/blob/c2c1f193d4531917f6939e2f8aaf75d8a7979d27/MyCapytain/resources/texts/local/capitains/cts.py#L71 ) to say that texts have not the right passage ID...
Need to fix that ASAP !

**Comment by PonteIneptique** [comment]
A good way to contribute here would be the create a specific error (Like PassageIdError) and add a test for it.

**Comment by sonofmun** [comment]
How about a more specific error like `CitationDepthError`?

**Comment by PonteIneptique** [comment]
Completely okay with this :)

**Comment by sonofmun** [comment]
On the other hand, how about using the existing `UnknownObjectError`: "This error is thrown when an object does not exist in an inventory or in an API"? I can add a message to it to in cts.py to make it clear that the citation depth was the problem.

**Comment by PonteIneptique** [comment]
I'd probably keep this apart though. You could inherit it though 1

**Comment by PonteIneptique** [comment]
Fixed
