### ISSUE TITLE
Metadata graph only includes one entry for each type of information

### ISSUE THREAD

**Issue by sonofmun** [Capitains/MyCapytain#181]
If I get readableDescendents from a top-level collection (from the CollectionDispatcher), it appears to return either the edition/translation language code or the text of one of the two dc:language elements that we have in the metadata files. (All of our `__cts__.xml` files have Deutsch and Latein as text values for the dc:language elements.)
But when I get readableDescendents from a urn (e.g., urn:cts:formulae:zuerich), then I always get the edition/translation language tag.
And the command I am using is:
`self.resolver.getMetadata(collection.id).readableDescendants)` (self.resolver is NautilusCTSResolver)
So when "collection.id" is a top-level collection, then I get one of the three, seemingly at random (as if they were dict.keys()).
But when "collection.id" is a urn, then I always get "lat", i.e., the expected result.

**Comment by PonteIneptique** [comment]
Hey.
First idea that comes through my mind, at parsing, the metadata are not stored ni the rdflib graph. Which means they are only connected to the instance of the object. Check this track potentially ? try to make a diff on `id(from_urn)` and `id(from_instance)` first.

**Comment by sonofmun** [comment]
I have encountered something similar which may shed some light on this. When I get the `lang` of a readableDescendant, it is always the `xml:lang` attribute on the `ti:work` element when it is an edition, but it is randomly the `xml:lang` attribute on the `ti:translation` element or one of the two `DC:language` attributes that I have in `cpt:structured-metadata`. My guess would be that when the metadata is parsed, the xpath goes through these tags in a random order and fills the `lang` with the last one it goes through. The thing that doesn't make sense, though, is why this would sometimes be assigned the value of the `xml:lang` on `ti:translation`. I can't precisely track where this comes from but it starts here: https://github.com/Capitains/MyCapytain/blob/b11bbf6b6ae141fc02be70471e3fbf6907be6593/MyCapytain/resolvers/cts/local.py#L460-L468.

**Comment by sonofmun** [comment]
OK. More digging has shown that the problem is not in the graph. The graph has all of the triples. The problem was that I was serializing the graph as JSON, which set the key as the object (e.g., dc:editor) and thus could only have a single value for that key. Serializing it in XML showed that all of the triples were there. So now I need to look at how the, e.g., `metadata.get_single` works to find out if it is querying from the JSON or if it is randomly selecting from the XML (or some other format).
