### ISSUE TITLE
Complex xpath in the refsDecl fail in MyCapitain

### ISSUE THREAD

**Issue by sonofmun** [Capitains/MyCapytain#40]
Complex xpath expressions which refer to two different attributes on a single node fail in MyCapitain.  Example.

    xpath("/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='2' and @subtype='section']"

This works in lxml but fails in MyCapitain.

**Comment by PonteIneptique** [comment]
I'll try to fix this one ASAP.
