### ISSUE TITLE
MyCapytain.resources

### ISSUE THREAD

**Issue by annakrohn** [Capitains/MyCapytain#45]
Unless I'm completely misunderstanding what I should be doing in Python (I still don't know it well so that could be true), I should be able to import MyCapytain.resources.text.api and then create a Text object that I can call the methods on. But I can't.
```
import MyCapytain.resources.texts.api
*** ImportError: No module named past.builtins
```
I can import up until text, but then I can't access api.py,
```
test=MyCapytain.resources.texts.api.Text(orig_uri, endpt) 
*** AttributeError: 'module' object has no attribute 'api'.  
```
I think it might partially be because the \__init\__.py  in texts is empty, but I can't use anything in resources.proto either. I can, however, import MyCapytain.endpoints.proto without issue and create an endpoint successfully.

**Comment by PonteIneptique** [comment]
Ok, could you give me more informations ?

- Python version
- Current packages available in the environment (`pip freeze`)

**Comment by annakrohn** [comment]
Python version should be 2.7

Pip freeze:
Babel==2.0
Flask==0.10.1
Flask-Babel==0.9
Flask-Bower==1.0.1
Flask-Cache==0.13.1
Flask-Cors==2.0.0
Flask-Markdown==0.3
Flask-PyMongo==0.3.1
itsdangerous==0.24
Jinja2==2.8
Markdown==2.6.3
MarkupSafe==0.23
MyCapytain==0.0.7
pymongo==2.8.1
pytz==2015.4
requests==2.8.1
requests-cache==0.4.9
six==1.10.0
speaklater==1.3
Werkzeug==0.10.4

**Comment by PonteIneptique** [comment]
Could you try to update to MyCapytain==0.0.9 ?

**Comment by annakrohn** [comment]
MyCapytain 0.0.9 is working much better, thank you.

But now I'm having issues understanding what needs to happen.

    from MyCapytain.endpoints import cts5
    from MyCapytain.resources.texts import api
    from MyCapytain.common import reference
    
    orig_uri = 'urn:cts:greekLit:tlg0032.tlg005.perseus-grc1'
    cts=cts5.CTS('http://services2.perseids.org/exist/restxq/cts?request=GetCapabilities&inv=annotsrc')
    test=api.Text(orig_uri, cts)
    ref = reference.Reference(reference='1-2')
    

Attempting `passg = test.getPassage(ref)` results in the error: `*** IndexError: list index out of range`
What am I missing?

**Comment by PonteIneptique** [comment]
Oh, yes, my bad, forgot this. I'll have a look at it today or tomorrow...

**Comment by PonteIneptique** [comment]
Here you go

```python
from MyCapytain.endpoints import cts5
from MyCapytain.resources.texts.api import Text

# We set the variable up, as if we were in a function
# This URN won't work (urn:cts:greekLit:tlg0032.tlg005.perseus-grc1) because it has no TEI namespace
urn = 'urn:cts:latinLit:phi1294.phi002.perseus-lat2'
ref = "1.1-1.2"

# We set the api up. Endpoint takes one required argument
#  (the URI) and one inventory as optional argument
cts = cts5.CTS('http://services2.perseids.org/exist/restxq/cts', inventory="nemo")

# We set up a text object to be able to retrieve passage of it
# Text in API modules takes endpoint as resource and URN as param

text = Text(urn=urn, resource=cts)

# We use the method getPassage which takes a reference argument
passage = text.getPassage(reference=ref)

# Passage then has different methods and properties
# Most of them (except next, prev and prevnext properties) are inherited from MyCapytain.resources.texts.tei.Text
# For example
print(passage.text(exclude=["note", "head"]))  # Will get the text without "note" and "head" TEI nodes
print(passage.xml)  # The xml property can be used as an argument for XSLT for example
```

**Comment by PonteIneptique** [comment]
The URN given won't work because original file is not in TEI namespace
https://github.com/PerseusDL/canonical-greekLit/blob/master/data/tlg0032/tlg005/tlg0032.tlg005.perseus-grc1.xml

**Comment by annakrohn** [comment]
Okay, thank you, this all makes sense!
