### ISSUE TITLE
Should the new getPassage (fix for #58) become the norm ?

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#59]
Hey @balmas @sonofmun ,

Right now, when you do getPassage on a local node with the local.Text, you only get the local node (which is quicker because it's a simple xpath result). You do not get a rebuilt tree from the root. The bad side of it is that it does not takes range.

On the other hand, the new function (or, to be more precise, the same function with hypercontext=True), rebuilds the tree (takes longer) but takes range. The result is lxml node for the moment (Not a passage) because range are not accepted right now in our local.getvalidreff. 

I am wondering if the new system should become the default one (ie supports range but takes more time). This might be a jump to 0.1.0 because this kind of change is big structurally...

**Comment by balmas** [comment]
all things being equal it seems to me that it would be better to support a retrieval that can deal with a range as the default and make the more performant one that works only with a passage be something you request as an option

**Comment by sonofmun** [comment]
I agree with Bridget here.  The one that does more, even if it is a bit slower, should be preferred.  Unless, of course, the difference in speed is enormous (e.g., .1 seconds vs. 5 seconds for a search).

**Comment by PonteIneptique** [comment]
Thanks for your feedback.
This mean that 0.0.10 will be 0.1.0 as the change will be structural.

**Comment by PonteIneptique** [comment]
Fixed #70
