### ISSUE TITLE
Add pickles methods for Inventory resources

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#69]
This is required by Redis Cache for example. If we want MyCapytain to be used at prod level, dict printing and pick should be supported.

**Comment by PonteIneptique** [comment]
Implies pickle for Citation and Metadata as well

**Comment by balmas** [comment]
https://docs.python.org/3.4/library/pickle.html (for those of us for whom pickles are just cucumbers)

**Comment by PonteIneptique** [comment]
You just made my day ! :)

**Comment by PonteIneptique** [comment]
*Important note* : Adding pickle, I moved Resource.parents to list instead of tuple.

**Comment by PonteIneptique** [comment]
Fixed #70
