### ISSUE TITLE
document the URN.upTo function 

### ISSUE THREAD

**Issue by balmas** [Capitains/MyCapytain#80]
document the URN.upTo function including examples of how to use it with the URN constants

**Comment by PonteIneptique** [comment]
If you are okay @balmas , I'd say it's fixed in #82

**Comment by balmas** [comment]
I'm a little confused. I don't see any reference to the upTo function in that PR

**Comment by PonteIneptique** [comment]
Because I forgot to. Look at the new doc :')

Le 19 sept. 2016 6:55 PM, "Bridget Almas" <notifications@github.com> a
écrit :

**Comment by PonteIneptique** [comment]
Closed by #82

**Comment by balmas** [comment]
agreed it's fixed in the new doc :)
