### ISSUE TITLE
Implement immutable classes representing different CTS resources.

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#88]

**Comment by PonteIneptique** [comment]
I think it would be great if it uses something like that ( http://stackoverflow.com/questions/4828080/how-to-make-an-immutable-object-in-python ) if it is picklable.

Candidates : 
- PrevNext(prev, next)
- Passage(xml, urn)
- Reffs([str_urn])
- Metadata(TextInventoryResource)

**Comment by PonteIneptique** [comment]
Any thing I might have left out @balmas ?

**Comment by balmas** [comment]
I agree with this idea, and I can't think of anything you're missing off the top of my head.

**Comment by PonteIneptique** [comment]
Not really necessary in the end. Could be reopen one day
