### ISSUE TITLE
Have a new Resolver Class

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#90]
Based on the discussion in #89 and in #88, the need for a class type that would return object instead of bytes is fairly clear (including the fact that Nemo and Nautilus would make use of that).

The problem with adding a level of children in the class hierarchy of retriever is that it would probably introduce breaking changes at one level in the whole MyCapytain world. To prevent this, I would rather have Resolver that use Retrievers instead of bonding them by children-parent relationships.

Feel free to chime in @fbaumgardt @balmas

**Comment by balmas** [comment]
can you add a little sequence and/or class diagram that shows the interaction between resolvers, requesters and retrievers?

**Comment by PonteIneptique** [comment]
Sorry, I messed up by writing. I meant Resolvers that use current retrievers. Retrievers are meant to retrieve some kind of resource in any format. Resolver can use retrievers to performs Query to give MyCapytain Objects

**Comment by PonteIneptique** [comment]
Fixed with 2.0.0b0 in #95 : MyCapytain.resolvers
