### ISSUE TITLE
Graph Object

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#91]
The graph object represent the situation of an object in the tree, it has the following properties : 
- parent (Unique ID)
- previous (Previous Id)
- next (Next Id)
- children (List of ID)
- id (Id of current node)

Use case : 
- I want to be able to navigate the same way from a passage to the other and cache the information
- I want to know where I am in the Graph to retrieve other informations
- I want a common object for any representation of a textual node

**Comment by PonteIneptique** [comment]
I have one thing against this architecture : Graph has no Graph has children but IDs. Should it have only Graph as children, siblings and parents, even so they are nearly only empty ?

Also, should Graph be simply named PassageId ?

**Comment by PonteIneptique** [comment]
Questions for @fbaumgardt and @balmas 

NB : I think we need a hackathon.

**Comment by balmas** [comment]
does Graph == Passage ?

**Comment by PonteIneptique** [comment]
Graph would only contain Identifiers, not content.

**Comment by PonteIneptique** [comment]
Done since #95
