### ISSUE TITLE
What should getSiblingsId and getReffs return ?

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#97]
# Situation

When one user wants to get passage's siblings identifier or children' identifiers, we used to return full URN. *eg* : 

```
GetValidReff(urn:cts:latinLit:phi1294.phi002.perseus-lat2:1.1) -> 
   urn:cts:latinLit:phi1294.phi002.perseus-lat2:1.1.1
   urn:cts:latinLit:phi1294.phi002.perseus-lat2:1.1.2
   urn:cts:latinLit:phi1294.phi002.perseus-lat2:1.1.3
   urn:cts:latinLit:phi1294.phi002.perseus-lat2:1.1.4
```

This is a situation that I have never really liked in CTS, and I think we left in DTS by separating clearly in requests Subreference and Text Identifier (afaik), ie, DTS should be something like : 

```
getReffs(urn:cts:latinLit:phi1294.phi002.perseus-lat2, 1.1) -> 
   1.1.1
   1.1.2
   1.1.3
   1.1.4
```

Because whatever happens, you asked for subreference identifiers, not full identifiers. This avoids redundancy, memory loads (even small but still) and could reduce communication cost (even with compressions)

# Implementation
Right now, there is a discrepancy between my API Resolver and my Local Resolver. Before going further, I'd like to see what you think. My feeling is that we should follow the second one (DTS Model).

# Question 
Should we return full urn when someone ask for a subreference sibling identifier or a subreference list of children identifiers, or should we return subreference only ?

**Comment by PonteIneptique** [comment]
Additional reason why I think returning only subreference makes sense : there is no need to reparse the response to remake a getPassage in DTS.

**Comment by balmas** [comment]
This seems reasonable to me

**Comment by fbaumgardt** [comment]
I have sat on this for a while and I think I'd prefer a more stateless solution. Which could still be accomplished without the redundancy of the CTS response, but instead by adding a header with the base URN. What do you think about that?

Ideally this would be done in a way that allows for packing multiple requests into one, e.g. for an edition and a translation. Not that it needs to be part of the specs, but it comes at no additional cost.

**Comment by balmas** [comment]
agree

**Comment by PonteIneptique** [comment]
@fbaumgardt Agree but I feel like your comment relates more on the HTTP API Standard (/api/dts/reffs/1234) than on the library standard (ie Text(id=1234).getReffs() -> a, b, c, d). But I might be mistaken

**Comment by fbaumgardt** [comment]
You're right!

**Comment by PonteIneptique** [comment]
Good, because the statement felt weird to me :dancing_men:
